# ensure running in a container for fast boot
dist: "trusty"
sudo: false

# these are executed in order.  each must pass for the next to be run
stages:
  - precache # warm up cache for default Node.js version
  - lint # lint code and docs
  - test # all tests

#defaults
language: node_js
node_js: "node"

install: npm install -g lerna --no-package-lock && npm run postinstall
cache:
  directories:
    - node_modules
    #- ~/.npm # cache npm's cache
    #- ~/cached-bins # cache latest npm and lerna

jobs:
  include:
    - script: npm run coverage
      after_success: npm run coveralls
      env: "COVERAGE=true"

    - &node
      script: npm run test
      node_js: "lts/*"

    - stage: lint
      script: npm run lint

    - stage: precache
      script: true

notifications:
  email: false
