sudo: false
language: node_js
cache:
  directories:
    - node_modules
    - $HOME/.npm
notifications:
  email: false
before_install:
  - npm i -g npm@latest
env:
  global:
    - NODE_NO_WARNINGS=1
matrix:
  fast_finish: true
node_js:
  - 'lts/*'
  - 'node'
env:
  - TASK=lint
  - TASK=test
  - TASK=coverage
script:
  - npm run $TASK
after_success:
  - cat apps/*/coverage/lcov.info | npx coveralls
