sudo: required
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '8'
env:
  - TASK=lint
  - TASK=test
  - TASK=coverage
install:
  - travis_wait npm i
before_script:
  - npm prune
  - npm run link:shared
script:
  - npm run $TASK
after_success:
  - cat apps/*/coverage/lcov.info | npx coveralls
