sudo: required
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
before_install:
  - npm i -g npm@latest
node_js:
  - 'lts/*'
  - 'node'
env:
  - TASK=lint
  - TASK=test
  - TASK=coverage
install:
  - travis_wait npm i
before_script:
  - npm prune
  - npm run link:shared
script:
  - npm run $TASK
after_success:
  - cat apps/*/coverage/lcov.info | npx coveralls
