sudo: required
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '8'
env:
  - TASK=test
  - TASK=lint
  - TASK=coverage
before_script:
  - npm prune
  - ganache-cli
script:
  - npm run $TASK